expect ROOT being owned by uid=0
Also, add an `overlay` helper for enabling persistent changes through 9p
transport when using applications that need mmap (e.g. `rpm`).

Also, refactor bin/vng/start-vm and expand bin/vng/cmd for manual use.

diff --git a/bin/rootfs/mount b/bin/rootfs/mount
--- a/bin/rootfs/mount
+++ b/bin/rootfs/mount
@@ -37,8 +37,8 @@ ensure_resolv_conf_target() {
 		return 0
 	fi
 
-	touch "$target" || {
-		echo "ERROR: unable to create $target as $(id -un)" >&2
+	"$BIN"/run --as-root touch "$target" || {
+		echo "ERROR: unable to create $target" >&2
 		exit 1
 	}
 }
