install: receive a list in lookup_package()
sles -> tumbleweed

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -2,6 +2,7 @@
 
 auto_install=
 declare -A fallback_map_files=()
+declare -a pkg_files=()
 lookup_package_result=
 while [[ $# -gt 0 ]]; do
 	case "$1" in
@@ -38,32 +39,35 @@ use_root_install() {
 }
 
 lookup_package() {
-	local map_file=$1
-	local dep=$2
-	local pkg
+	local dep=$1
+	local map_file pkg
+	local map_names=()
 
-	if [[ -e $map_file ]] && pkg=$(
-		awk -v key="$dep" '
-		$0 ~ /^[[:space:]]*#/ || NF == 0 { next }
-		$1 == key {
-			found = 1
-			if (NF >= 2) {
-				print $2
+	for map_file in "${pkg_files[@]}"; do
+		map_names+=("$(basename "$map_file")")
+		if [[ -e $map_file ]] && pkg=$(
+			awk -v key="$dep" '
+			$0 ~ /^[[:space:]]*#/ || NF == 0 { next }
+			$1 == key {
+				found = 1
+				if (NF >= 2) {
+					print $2
+				}
+				exit
 			}
-			exit
-		}
-		END {
-			if (!found) {
-				exit 1
+			END {
+				if (!found) {
+					exit 1
+				}
 			}
-		}
-	' "$map_file"
-	); then
-		lookup_package_result=$pkg
-		return 0
-	fi
+		' "$map_file"
+		); then
+			lookup_package_result=$pkg
+			return 0
+		fi
+	done
 
-	fallback_map_files[$dep]=$(basename "$map_file")
+	fallback_map_files[$dep]="${map_names[*]}"
 	lookup_package_result=$dep
 }
 
@@ -126,14 +130,14 @@ esac
 
 case "$ID" in
 debian)
-	pkg_file="$BIN"/../pkg/debian
+	pkg_files=("$BIN"/../pkg/debian)
 	check_cmd=(dpkg -s)
 	repair_cmd=(dpkg --configure -a)
 	update_cmd=(env DEBIAN_FRONTEND=noninteractive apt-get update)
 	install_cmd=(env DEBIAN_FRONTEND=noninteractive apt-get install -y --allow-unauthenticated --force-yes)
 	;;
 opensuse-tumbleweed)
-	pkg_file="$BIN"/../pkg/tumbleweed
+	pkg_files=("$BIN"/../pkg/tumbleweed)
 	check_cmd=(rpm -q --whatprovides)
 	repair_cmd=()
 	update_cmd=(zypper --gpg-auto-import-keys refresh)
@@ -142,10 +146,10 @@ opensuse-tumbleweed)
 sles)
 	case "${VERSION_ID:-}" in
 	# 12*)
-	# 	pkg_file="$BIN"/../pkg/sles12
+	# 	pkg_files=("$BIN"/../pkg/sles12 "$BIN"/../pkg/tumbleweed)
 	# 	;;
 	*)
-		pkg_file="$BIN"/../pkg/sles
+		pkg_files=("$BIN"/../pkg/sles "$BIN"/../pkg/tumbleweed)
 		;;
 	esac
 	check_cmd=(rpm -q --whatprovides)
@@ -158,13 +162,15 @@ sles)
 	;;
 esac
 
-if [[ ! -e $pkg_file ]]; then
-	echo "WARN: File not found: $pkg_file" >&2
-fi
+for pkg_file in "${pkg_files[@]}"; do
+	if [[ ! -e $pkg_file ]]; then
+		echo "WARN: File not found: $pkg_file" >&2
+	fi
+done
 
 packages=()
 for dep in "$@"; do
-	lookup_package "$pkg_file" "$dep"
+	lookup_package "$dep"
 	[[ -n $lookup_package_result ]] && packages+=("$lookup_package_result")
 done
 
